conky.config = {
    alignment = 'top_right',
    xinerama_head = 1,  -- Chọn monitor eDP-2
    gap_x = 10,
    gap_y = 40,
    background = false,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'white',
    use_xft = true,
    font = 'DejaVu Sans Mono:size=10',
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'override',
    own_window_transparent = true,
    update_interval = 1.0,
}

conky.text = [[
${color grey}Refresh Rate:$color ${exec xrandr | grep 'eDP-2' -A1 | tail -1 | awk '{print $1}' | grep -oP '[\d.]+(?=\*)'}Hz

${color grey}CPU:$color $cpu% ${cpubar 4}
${color grey}RAM:$color $mem/$memmax
${color grey}GPU Temp:$color ${exec nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader}°C
]]
