#!/bin/bash
export QT_QPA_PLATFORM=xcb
export QT_QPA_PLATFORMTHEME=xdgdesktopportal

# Check if this is a forward-search or execute-command call
if [[ "$*" == *"--forward-search"* ]] || [[ "$*" == *"--execute-command"* ]]; then
    # Just pass through, don't toggle
    exec /usr/bin/sioyek-bin "$@"
else
    # Normal open - start and toggle
    /usr/bin/sioyek-bin "$@" &
    
    # Send toggle commands
    /usr/bin/sioyek-bin --execute-command toggle_synctex
    /usr/bin/sioyek-bin --execute-command toggle_custom_color
fi