# -----------------------------------------------------
# ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█
#
# name "minimal"
#
# -----------------------------------------------------

animations {
  enabled = yes

  bezier = liner, 1, 1, 1, 1
  bezier = overshot, 0.05, 0.9, 0.1, 1
  bezier = smoothOut, 0.5, 0, 0.99, 1
  bezier = smoothIn, 0.5, -0.5, 0.68, 1

  animation = windows, 1, 8, default, slide
  animation = windowsIn, 1, 5, default, slide top
  animation = windowsOut, 1, 5, default, slide bottom
  animation = layersIn, 1, 5, default, slide top
  animation = layersOut, 1, 5, default, slide top
  animation = windowsMove, 1, 5, default, slide
  animation = border, 1, 1, liner
  animation = workspaces, 1, 8, overshot, slide

  # animations for -git or version >0.42.0
  animation = workspacesIn, 1, 8, overshot, slidehor
  animation = workspacesOut, 1, 8, overshot, slidehor
}
workspace_wraparound = true
