Net/ThemeName "Colloid-Dark-Gruvbox"
Net/IconThemeName "Delight 2"
Gtk/CursorThemeName "Win11OSX"
Net/EnableEventSounds 1
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 0
Xft/HintStyle "hintnone"
Xft/RGBA "rgb"
